export const demoProducts = [
  {
    _id: 'midnight-arabica',
    slug: 'midnight-arabica',
    name: 'Midnight Arabica',
    description: 'An enigmatic blend sourced from the misty highlands of Huila, Colombia. Deep, mysterious, and profoundly satisfying with dark sweetness and a smoky finish.',
    price: 32,
    oldPrice: 38,
    category: 'Special Reserve',
    roast: 'Dark',
    origin: 'Colombia',
    tastingNotes: ['Chocolate', 'Caramel', 'Smoky Toffee'],
    image: '/coffee/product-midnight-detail.png',
    cardImage: '/coffee/product-midnight-card.png',
    countInStock: 34,
    rating: 4.9,
    numReviews: 128,
    featured: true,
    weight: '250g',
  },
  {
    _id: 'vanilla-cold-brew',
    slug: 'vanilla-cold-brew',
    name: 'Vanilla Cold Brew',
    description: '12-hour steeped concentrate with Madagascan vanilla pods, smooth body, and a creamy coffee-shop finish over ice.',
    price: 18.5,
    oldPrice: 22,
    category: 'Cold Brew',
    roast: 'Medium',
    origin: 'Madagascar',
    tastingNotes: ['Vanilla', 'Cream', 'Brown Sugar'],
    image: '/coffee/product-vanilla-coldbrew.png',
    cardImage: '/coffee/product-vanilla-coldbrew.png',
    countInStock: 52,
    rating: 4.8,
    numReviews: 76,
    featured: true,
    weight: '500ml',
  },
  {
    _id: 'golden-espresso',
    slug: 'golden-espresso',
    name: 'Golden Espresso',
    description: 'Our signature blend with intense crema and notes of toasted hazelnut, created for clean shots and velvet lattes.',
    price: 42,
    oldPrice: 0,
    category: 'Espresso',
    roast: 'Dark',
    origin: 'Brazil',
    tastingNotes: ['Hazelnut', 'Crema', 'Cacao'],
    image: '/coffee/product-golden-espresso.png',
    cardImage: '/coffee/product-golden-espresso.png',
    countInStock: 28,
    rating: 5,
    numReviews: 91,
    featured: true,
    weight: '250g',
  },
  {
    _id: 'ethiopian-heirloom',
    slug: 'ethiopian-heirloom',
    name: 'Ethiopian Heirloom',
    description: 'Light roast reserve with citrus lift, floral aroma, and a clean tea-like finish for slow pour-over rituals.',
    price: 28,
    oldPrice: 34,
    category: 'Whole Bean',
    roast: 'Light',
    origin: 'Ethiopia',
    tastingNotes: ['Citrus', 'Jasmine', 'Honey'],
    image: '/coffee/product-heirloom.png',
    cardImage: '/coffee/product-heirloom.png',
    countInStock: 22,
    rating: 4.7,
    numReviews: 54,
    featured: false,
    weight: '250g',
  },
  {
    _id: 'artisan-precision-grinder',
    slug: 'artisan-precision-grinder',
    name: 'Artisan Precision Grinder',
    description: 'Matte black grinder built for consistent extraction, from espresso fine to French press coarse.',
    price: 185,
    oldPrice: 210,
    category: 'Hardware',
    roast: 'Gear',
    origin: 'CoffeeVerse Studio',
    tastingNotes: ['Precision', 'Matte Black', 'Barista Grade'],
    image: '/coffee/cart-grinder.png',
    cardImage: '/coffee/cart-grinder.png',
    countInStock: 11,
    rating: 4.9,
    numReviews: 33,
    featured: false,
    weight: 'Matte black',
  },
  {
    _id: 'midnight-velvet-espresso',
    slug: 'midnight-velvet-espresso',
    name: 'Midnight Velvet Espresso',
    description: 'A dramatic dark roast with toasted cacao, heavy crema, and a long caramel finish.',
    price: 24,
    oldPrice: 30,
    category: 'Ground Coffee',
    roast: 'Dark',
    origin: 'House Blend',
    tastingNotes: ['Cacao', 'Crema', 'Molasses'],
    image: '/coffee/cart-velvet-espresso.png',
    cardImage: '/coffee/cart-velvet-espresso.png',
    countInStock: 44,
    rating: 4.6,
    numReviews: 60,
    featured: false,
    weight: '250g',
  },
];

export function findDemoProduct(id) {
  return demoProducts.find((product) => product._id === id || product.slug === id);
}
